name: Python CI

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Check out code
        uses: actions/checkout@v4

      # Step 2: Set up Python Environment
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          
      # Step 3: Display Python and pip versions for debugging
      - name: Display versions
        run: |
          python --version
          pip --version

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "requirements.txt not found, installing default packages"
            pip install pytest
          fi

      # Step 5: Run tests
      - name: Run tests
        run: |
          python -m pytest -v
