name: Python CI

# Trigger the workflow on any push to the main branch or pull request
on:
  push:
    branches: 
    - main
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Check out code
        uses: actions/checkout@v4  # Updated to latest version

      # Step 2: Set up Python Environment (FIXED - using correct action)
      - name: Set up Python
        uses: actions/setup-python@v4  # Changed to setup-python action
        with:
          python-version: '3.8'
          
      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Fixed typo: --ugrade -> --upgrade
          pip install -r requirements.txt

      # Step 4: Run tests
      - name: Run tests
        run: pytest
